my_string = input('Введите любой текст ')
print('Количество символов: ', len(my_string))
print(my_string.upper())
print(my_string.lower())
print(my_string.replace(' ', ''))
print('Первый символ:', my_string[0])
print("Последний символ:", my_string[-1])