# Generated by Django 4.2.17 on 2024-12-11 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task1', '0002_alter_buyer_balance_alter_game_cost_alter_game_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='username',
            new_name='name',
        ),
    ]
